name: jazzy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
      - cron: '0 0 * * 6'  
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
      fail-fast: false
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.7.13
        with:
          required-ros-distributions: jazzy
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.4.3
        with:
          package-name: summit_utils
          target-ros2-distro: jazzy
          skip-test: true
          colcon-defaults: |
            {
              "build": {
                "packages-up-to": true
              }
            }